apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        {{- range $key, $val := .Values.config }}
          - name: {{ $key }}
            value: {{ $val | quote }}
        {{- end }}
          - name: ES_USERNAME
            valueFrom:
              secretKeyRef:
                name: fluentd-secrets
                key: ES_USERNAME
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fluentd-secrets
                key: ES_PASSWORD
          - name: ES_HOST
            valueFrom:
              secretKeyRef:
                name: fluentd-secrets
                key: ES_HOST
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: config-volume
          mountPath: /fluentd/etc/
        - name: varlog
          mountPath: /var/log
        - name: dockerlogs
          mountPath: /var/lib/docker/containers
          readOnly: true

      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: dockerlogs
        hostPath:
          path: /var/lib/docker/containers
