apiVersion: v1
kind: Secret
metadata:
  name: fluentd-secrets
type: Opaque
data:
  ES_USERNAME: {{ .Values.secrets.ES_USERNAME | b64enc | quote }}
  ES_PASSWORD: {{ .Values.secrets.ES_PASSWORD | b64enc | quote }}
  ES_HOST: {{ .Values.secrets.ES_HOST | b64enc | quote }}
